{{- if .Values.persistence.stash.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "nestjs-example.fullname" . }}-backup-init
  labels:
    app: {{ template "nestjs-example.name" . }}-backup-init
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: '3'
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  strategy:
    type: {{ .Values.config.updateStrategy }}
  template:
    metadata:
      labels:
        app: {{ template "nestjs-example.name" . }}-backup-init
        release: {{ .Release.Name }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kubectl
          image: codejamninja/stash-cli:0.0.1
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              kubectl stash cp repository {{ .Values.persistence.stash.repository }} --namespace=kube-system --to-namespace={{ .Release.Namespace }}
---
apiVersion: stash.appscode.com/v1beta1
kind: BackupBatch
metadata:
  name: {{ template "nestjs-example.fullname" . }}
  labels:
    app: {{ template "nestjs-example.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  repository:
    name: {{ .Values.persistence.stash.repository | quote }}
  paused: {{ .Values.persistence.stash.paused }}
  schedule: {{ .Values.persistence.stash.schedule | quote }}
  retentionPolicy:
    name: retention-policy
    keepLast: {{ .Values.persistence.stash.keepLast }}
    prune: true
  members:
    {{- if (and .Values.config.postgres.internal (not (and (eq .Values.config.postgres.terminationPolicy "Pause") .Values.config.postgres.pause))) }}
    - target:
        ref:
          apiVersion: apps/v1
          kind: AppBinding
          name: {{ template "nestjs-example.fullname" . }}-postgres
      task:
        name: postgres-backup-{{ .Values.config.postgres.version }}
    {{- end }}
    {{- if (and .Values.config.redis.internal (not (and (eq .Values.config.redis.terminationPolicy "Pause") .Values.config.redis.pause))) }}
    - target:
        ref:
          apiVersion: apps/v1
          kind: AppBinding
          name: {{ template "nestjs-example.fullname" . }}-redis
      task:
        name: redis-backup-{{ .Values.config.redis.version }}
    {{- end }}
    - target:
        ref:
          apiVersion: apps/v1
          kind: Deployment
          name: {{ template "nestjs-example.fullname" . }}-redis
        volumeMounts:
          - name: data
            mountPath: /_data
        paths:
          - /_data
{{- end }}
