apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nestjs-example.fullname" . }}-nestjs-example
  labels:
    app: {{ template "nestjs-example.name" . }}-nestjs-example
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ template "nestjs-example.fullname" . }}-nestjs-example
          image: {{ .Values.images.nestjsExample.repository }}:{{ .Values.images.nestjsExample.tag }}
          imagePullPolicy: {{ .Values.config.imagePullPolicy }}
          ports:
            - name: container
              containerPort: 3000
          env: []
          livenessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
