version: '3.7'

services:
  dev:
    container_name: dev
    image: busybox
    command: tail -f /dev/null
    depends_on:
      - keycloak
      - postgres
      - redis

  app:
    container_name: ${NAME}
    image: ${IMAGE}:latest
    ports:
      - 5000:5000
    environment:
      DEBUG: '1'
      GRAPHQL_PLAYGROUND: '1'
      SWAGGER: '1'
      OTEL_SERVICE_NAME: nestjs-full-example
      LOG_FILE_NAME: /app/logs/nestjs-example.log
    volumes:
      - ./data/logs:/app/logs
    depends_on:
      - otel-collector
      - keycloak
      - postgres
      - redis

  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.0.4
    container_name: redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:19.0.3-legacy
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./realm-export.json:/tmp/realm-export.json:ro
      - ./providers:/opt/keycloak/providers
    entrypoint:
      - sh
      - -c
      - |
        /opt/keycloak/bin/kc.sh build
        IMPORT_FLAG_FILE=/opt/keycloak/imported.flag
        if [ "$${KEYCLOAK_IMPORT}" != "" ]; then
          if [ ! -f "$$IMPORT_FLAG_FILE" ]; then
            /opt/keycloak/bin/kc.sh import --file "$$KEYCLOAK_IMPORT"
            touch "$$IMPORT_FLAG_FILE"
          fi
        fi
        /opt/keycloak/bin/kc.sh start-dev
    environment:
      KEYCLOAK_IMPORT: /tmp/realm-export.json
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: P@ssw0rd

  tempo:
    image: grafana/tempo:1.0.1
    command: ['-config.file=/etc/tempo.yaml']
    volumes:
      - ./etc/tempo-local.yaml:/etc/tempo.yaml
      - ./data/tempo-data:/tmp/tempo
    ports:
      - '14268' # jaeger ingest, Jaeger - Thrift HTTP
      - '14250' # Jaeger - GRPC
      - '55680' # OpenTelemetry
      - '3100' # tempo
      - '6831/udp' # Jaeger - Thrift Compact
      - '6832/udp' # Jaeger - Thrift Binary

  loki:
    image: grafana/loki:2.2.1
    command: -config.file=/etc/loki/loki-local.yaml
    ports:
      - '3101:3100' # loki needs to be exposed so it receives logs
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces # send traces to Tempo
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    volumes:
      - ./etc/loki-local.yaml:/etc/loki/loki-local.yaml
      - ./data/loki-data:/tmp/loki

  promtail:
    image: grafana/promtail:2.2.1
    command: -config.file=/etc/promtail/promtail-local.yaml
    volumes:
      - ./etc/promtail-local.yaml:/etc/promtail/promtail-local.yaml
      - ./data/logs:/app/logs
    depends_on:
      - app
      - loki
  volume_exporter:
    image: mnadeem/volume_exporter
    command: ['--volume-dir=tempo:/tmp/tempo', '--volume-dir=logs:/app/logs', '--volume-dir=loki:/tmp/loki']
    volumes:
      - ./data/logs:/app/logs
      - ./data/tempo-data:/tmp/tempo
      - ./data/loki-data:/tmp/loki
    ports:
      - 9889:9888

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./etc/prometheus.yaml:/etc/prometheus.yaml
    entrypoint:
      - /bin/prometheus
      - --config.file=/etc/prometheus.yaml
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:8.1.0-ubuntu
    volumes:
      - ./data/grafana-data/datasources:/etc/grafana/provisioning/datasources
      - ./data/grafana-data/dashboards-provisioning:/etc/grafana/provisioning/dashboards
      - ./data/grafana-data/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
      - tempo
      - loki
      - volume_exporter

  otel-collector:
    image: otel/opentelemetry-collector-dev:latest
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      - ./etc/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - '1888:1888' # pprof extension
      - '8888:8888' # Prometheus metrics exposed by the collector
      - '8889:8889' # Prometheus exporter metrics
      - '13133:13133' # health_check extension
      - '4317' # OTLP gRPC receiver
      - '55670:55679' # zpages extension
    depends_on:
      - tempo
      - prometheus

volumes:
  postgres:
    name: postgres-${NAME}
  redis:
    name: redis-${NAME}
