name: nestjs-example
home: https://github.com/codejamninjs/nestjs-example
icon: 
version: 0.0.1
appVersion: latest
description: 'nestjs keycloak and crud'
keywords:
  - nestjs-example
  - nestjs, crud, keycloak
sources:
  - https://github.com/codejamninjs/nestjs-example
maintainers:
  - name: 'Jam'
    email: jam@siliconhills.co
