images:
  nestjsExample:
    repository: codejamninja/nestjs-example
    tag: latest
  redis:
    repository: 6.0.8-alpine
    tag: latest

config:
  clusterProvider: infrastructure
  imagePullPolicy: Always
  updateStrategy: Recreate
  nestjsExample:
    baseUrl: ''
    hostname: ''
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
  redis:
    hostname: ''
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
  postgres:
    database: nestjs-example
    host: ''
    password: P@ssw0rd
    port: 5432
    url: ''
    username: postgres
  redis:
    host: ''
    password: ''
    port: 6379
    url: ''
    username: ''

service:
  nestjsExample:
    type: NodePort
    externalTrafficPolicy: Cluster
    nodePorts:
      http:
    lbPorts:
      http: 80
  redis:
    type: NodePort
    externalTrafficPolicy: Cluster
    nodePorts:
      http:
    lbPorts:
      http: 80

ingress:
  nestjsExample:
    certificate: ''
    enabled: false
    hostname: ''
    tls: false
    issuer:
      name: letsencrypt-staging

persistence:
  accessMode: ReadWriteOnce
  enabled: false
  storageClass: ''
  existingClaim:
    redis: ''
  size:
    redis: 1Gi
  velero:
    enabled: false
    restic: true
    schedule: '@midnight'

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
