apiVersion: v1
kind: Service
metadata:
  name: {{ template "nestjs-example.fullname" . }}-nestjs-example
  labels:
    app: {{ template "nestjs-example.name" . }}-nestjs-example
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if .Values.ingress.nestjs-example.enabled }}
  type: ClusterIP
  {{- else }}
  type: {{ .Values.service.nestjs-example.type }}
  {{- if (eq .Values.service.nestjs-example.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.nestjs-example.externalTrafficPolicy }}
  {{- end }}
  {{- end }}
  ports:
    - name: http
      port: {{ (eq .Values.service.nestjsExample.type "LoadBalancer") | ternary .Values.service.nestjsExample.lbPorts.http "80" }}
      targetPort: container
      {{- if (and (eq .Values.service.nestjsExample.type "NodePort") (not (empty .Values.service.nestjsExample.nodePorts.http))) }}
      nodePort: {{ .Values.service.nestjsExample.nodePorts.http }}
      {{- end }}
  selector:
    app: {{ template "nestjs-example.name" . }}-nestjs-example
    release: {{ .Release.Name }}
