apiVersion: v1
kind: Service
metadata:
  name: {{ template "nestjs-example.fullname" . }}-redis
  labels:
    app: {{ template "nestjs-example.name" . }}-redis
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: container
  selector:
    app: {{ template "nestjs-example.name" . }}-redis
    release: {{ .Release.Name }}
